routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/posts/{post}', ['as'=>'home.post', 'uses'=>'HomeController@post']);

Route::group(['middleware'=>'admin'], function(){
	// Route::get('/admin', ['as'=>'admin.index'], function(){
	// 	return view('admin.index');
	// });
	Route::get('/admin', ['as'=>'admin.index', 'uses'=>'AdminController@index']);

	Route::resource('admin/users', 'AdminUsersController');
	
	Route::resource('admin/posts', 'AdminPostsController');
	
	Route::resource('admin/categories', 'AdminCategoriesController');
	
	Route::resource('admin/photos', 'AdminPhotosController');
	
	Route::delete('admin/delete/photos', 'AdminPhotosController@deletePhotos');
	
	Route::get('admin/comments', 'AdminCommentsController@index')->name('comments.index');
	Route::get('admin/comments/{comment}', 'AdminCommentsController@show')->name('comments.show');
	Route::patch('admin/comments/{comment}', 'AdminCommentsController@update')->name('comments.update');
	Route::delete('admin/comments/{comment}', 'AdminCommentsController@destroy')->name('comments.destroy');

	
	Route::get('admin/comment/replies/{reply}', 'AdminCommentRepliesController@show')->name('replies.show');
	Route::patch('admin/comment/replies/{reply}', 'AdminCommentRepliesController@update')->name('replies.update');
	Route::delete('admin/comment/replies/{reply}', 'AdminCommentRepliesController@destroy')->name('replies.destroy');
	
	Route::get('/profile', ['as'=>'home.profile', 'uses'=>'HomeController@profile']);
});

Route::group(['middleware'=>'auth'], function(){
    Route::post('admin/comment/replies', 'AdminCommentRepliesController@store')->name('replies.store');
    Route::post('admin/comments', 'AdminCommentsController@store')->name('comments.store');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
	\UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::fallback(function(){
    return view('errors.404');
});

// Route::resource('admin/posts', 'AdminPostsController');

// Route::resource('admin/categories', 'AdminCategoriesController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','role_id','photo_id','is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function role(){
        return $this->belongsTo('App\Role');
    }

    public function photo(){
        return $this->belongsTo('App\Photo');
    }

    public function isAdmin(){
        if($this->role->name  == "administrator" && $this->is_active == 1){
            return true;
        }
        return false;
    }

    public function posts(){
        return $this->hasMany('App\Post');
    }

    public function getGravatarAttribute(){
        $hash = md5(strtolower(trim($this->attributes['email']))) . "?d=mm&s=";
        return "http://www.gravatar.com/avatar/$hash";
    }
}

resources/views/admin/users/create.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Create Users</h1>

    {!! Form::open(['method'=>'POST', 'action'=> 'AdminUsersController@store','files'=>true]) !!}
    
        <div class="row">
            <div class="col-sm-6">
                @include('includes.form_error')
            </div>
        </div>
        
        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class'=>'form-control'])!!}
        </div>

        <div class="form-group">
            {!! Form::label('email', 'Email:') !!}
            {!! Form::email('email', null, ['class'=>'form-control'])!!}
        </div>

        <div class="form-group">
            {!! Form::label('role_id', 'Role:') !!}
            {!! Form::select('role_id', $roles, 1, ['class'=>'form-control'])!!}
        </div>

        <div class="form-group">
            {!! Form::label('is_active', 'Status:') !!}
            {!! Form::select('is_active', array(1 => 'Active', 0=> 'Not Active'), 0 , ['class'=>'form-control'])!!}
        </div>
    
        <div class="form-group">
            {!! Form::label('photo_id', 'Photo:') !!}
            {!! Form::file('photo_id', null, ['class'=>'form-control'])!!}
        </div> 

        <div class="form-group">
            {!! Form::label('password', 'Password:') !!}
            {!! Form::password('password', ['class'=>'form-control'])!!}
        </div>


        <div class="form-group">
            {!! Form::submit('Create User', ['class'=>'btn btn-primary']) !!}
        </div>
        
       {{--  @include('includes.form_error') --}}

    {!! Form::close() !!}

 @endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.admin')

@section('content')



<h1>Edit User</h1>

<div class="row">
	<div class="col-sm-3">
		<img src="{{$user->photo ? $user->photo->file : 'http://placehold.it/400x400'}}" alt="" class="img-responsive img-rounded">
	</div>

	<div class="col-sm-9">
    
    <div class="row">
        <div class="col-sm-6">
            @include('includes.form_error')
        </div>
    </div>
    
    {!! Form::model($user, ['method'=>'PATCH', 'action'=> ['AdminUsersController@update', $user->id],'files'=>true]) !!}

    <div class="form-group">
        {!! Form::label('name', 'Name:') !!}
        {!! Form::text('name', null, ['class'=>'form-control'])!!}
    </div>

    <div class="form-group">
        {!! Form::label('email', 'Email:') !!}
        {!! Form::email('email', null, ['class'=>'form-control'])!!}
    </div>

    <div class="form-group">
        {!! Form::label('role_id', 'Role:') !!}
        {!! Form::select('role_id',  $roles , null, ['class'=>'form-control'])!!}
    </div>

    <div class="form-group">
        {!! Form::label('is_active', 'Status:') !!}
        {!! Form::select('is_active', array(1 => 'Active', 0=> 'Not Active'), null , ['class'=>'form-control'])!!}
    </div>

    <div class="form-group">
        {!! Form::label('photo_id', 'Photo:') !!}
        {!! Form::file('photo_id', null, ['class'=>'form-control'])!!}
    </div>

    <div class="form-group">
        {!! Form::label('password', 'Password:') !!}
        {{-- {!! Form::password('password', ['class'=>'form-control'])!!} --}}
        {!!Form::password('password', array('placeholder'=>'******', 'class'=>'form-control'))!!}
    </div>

    <div class="form-group">
        {!! Form::submit('Update User', ['class'=>'btn btn-primary col-sm-6']) !!}
    </div>

    {!! Form::close() !!}

    {!! Form::open(['method'=>'DELETE', 'action'=> ['AdminUsersController@destroy', $user->id]]) !!}

        <div class="form-group">
        {!! Form::submit('Delete user', ['class'=>'btn btn-danger col-sm-6']) !!}
        </div>

    {!! Form::close() !!}
    
	</div>
</div>

@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.admin')

@section('content')

	{{-- @if(Session::has('deleted_user'))
		<p class="bg-danger">{{session('deleted_user')}}</p>
	@endif --}}
	
	<h1>Users</h1>
	<table class="table">
	    <thead>
		    <tr>
		        <th>ID</th>
		        <th>Photo</th>
		        <th>Name</th>
	            <th>Email</th>
	            <th>Role</th>
	            <th>Status</th>
		        <th>Created</th>
	            <th>Updated</th>
		    </tr>
	    </thead>
	    <tbody>

	    	@if($users)
				@foreach($users as $user)
		           <tr>
		              	<td>{{$user->id}}</td>
		              	<td> <img height="50" src="{{$user->photo ? $user->photo->file : 'http://placehold.it/400x400'}}" alt="" ></td>
		              	<td><a href="{{route('users.edit', $user->id)}}">{{$user->name}}</a></td>
		              	<td>{{$user->email}}</td>
		              	<td>{{$user->role->name}}</td>
               			<td>{{$user->is_active == 1 ? 'Active' : 'Not Active' }}</td>
		           	  	<td>{{$user->created_at->diffForHumans()}}</td>
              			<td>{{$user->updated_at->diffForHumans()}}</td>
		           </tr>
            	@endforeach
			@endif
		</tbody>
	</table>

	<div class="row">
        <div class="col-sm-6 col-sm-offset-5">

            {{$users->render()}}

        </div>
    </div>
    
@endsection