routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/posts/{post}', ['as'=>'home.post', 'uses'=>'HomeController@post']);

Route::group(['middleware'=>'admin'], function(){
	// Route::get('/admin', ['as'=>'admin.index'], function(){
	// 	return view('admin.index');
	// });
	Route::get('/admin', ['as'=>'admin.index', 'uses'=>'AdminController@index']);

	Route::resource('admin/users', 'AdminUsersController');
	
	Route::resource('admin/posts', 'AdminPostsController');
	
	Route::resource('admin/categories', 'AdminCategoriesController');
	
	Route::resource('admin/photos', 'AdminPhotosController');
	
	Route::delete('admin/delete/photos', 'AdminPhotosController@deletePhotos');
	
	Route::get('admin/comments', 'AdminCommentsController@index')->name('comments.index');
	Route::get('admin/comments/{comment}', 'AdminCommentsController@show')->name('comments.show');
	Route::patch('admin/comments/{comment}', 'AdminCommentsController@update')->name('comments.update');
	Route::delete('admin/comments/{comment}', 'AdminCommentsController@destroy')->name('comments.destroy');

	
	Route::get('admin/comment/replies/{reply}', 'AdminCommentRepliesController@show')->name('replies.show');
	Route::patch('admin/comment/replies/{reply}', 'AdminCommentRepliesController@update')->name('replies.update');
	Route::delete('admin/comment/replies/{reply}', 'AdminCommentRepliesController@destroy')->name('replies.destroy');
	
	Route::get('/profile', ['as'=>'home.profile', 'uses'=>'HomeController@profile']);
});

Route::group(['middleware'=>'auth'], function(){
    Route::post('admin/comment/replies', 'AdminCommentRepliesController@store')->name('replies.store');
    Route::post('admin/comments', 'AdminCommentsController@store')->name('comments.store');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
	\UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::fallback(function(){
    return view('errors.404');
});

// Route::resource('admin/posts', 'AdminPostsController');

// Route::resource('admin/categories', 'AdminCategoriesController');

resources/views/includes/admin_nav.blade.php
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <!--Admin Top Navigation-->
    @include('includes.admin_top_nav')

    <!--Admin Side Navigation-->
    @include('includes.admin_side_nav')
    <!-- /.navbar-static-side -->
</nav>

resources/views/includes/admin_side_nav.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
            <li class="sidebar-search">
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                </div>
                <!-- /input-group -->
            </li>
            <li>
                <a href="/admin"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
            </li>

            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i>Users<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('users.index')}}">All Users</a>
                    </li>

                    <li>
                        <a href="{{route('users.create')}}">Create User</a>
                    </li>

                </ul>
                <!-- /.nav-second-level -->
            </li>

            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i> Posts<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('posts.index')}}">All Posts</a>
                    </li>

                    <li>
                        <a href="{{route('posts.create')}}">Create Post</a>
                    </li>

                    <li>
                        <a href="{{route('comments.index')}}">All Comments</a>
                    </li>

                </ul>
                <!-- /.nav-second-level -->
            </li>


            {{-- <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i>Categories<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('categories.index')}}">All Categories</a>
                    </li>

                    <li>
                        <a href="{{route('categories.create')}}">Create Category</a>
                    </li>

                </ul>
                <!-- /.nav-second-level -->
            </li>
--}}

            <li>
                <a href="{{route('categories.index')}}"><i class="fa fa-wrench fa-fw"></i> Categories</a>
            </li>    

            <li>
                <a href="#"><i class="fa fa-wrench fa-fw"></i>Photos<span class="fa arrow"></span></a>
                <ul class="nav nav-second-level">
                    <li>
                        <a href="{{route('photos.index')}}">All Photos</a>
                    </li>

                    <li>
                        <a href="{{route('photos.create')}}">Upload Photo</a>
                    </li>

                </ul>
                <!-- /.nav-second-level -->
            </li>

        </ul>

    </div>
    <!-- /.sidebar-collapse -->
</div>

resources/views/includes/admin_top_nav.blade.php
<div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Home</a>
    </div>
    <!-- /.navbar-header -->

    <!--TOP NAVIGATION-->
    <ul class="nav navbar-top-links navbar-right">
        
        <!-- /.dropdown -->
        <li class="dropdown">

            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>
                {{ Auth::user()->name }}
                <i class="fa fa-caret-down">
    
                </i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="{{ route('home.profile') }}"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li>
                <a href="{{ route('logout') }}"
                   onclick="event.preventDefault();
                                 document.getElementById('logout-form').submit();">
                    <i class="fa fa-sign-out fa-fw"></i> Logout
                </a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>

resources/views/includes/flash_messages.blade.php
<!-- Users -->
@if(Session::has('success_create_user_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_create_user_message')}}</p>
	</div>

@endif

@if(Session::has('success_update_user_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_update_user_message')}}</p>
	</div>

@endif

@if(Session::has('success_delete_user_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_delete_user_message')}}</p>
	</div>

@endif

<!-- Posts -->
@if(Session::has('info_create_category_first_message'))
	
	<div class="alert alert-info col-sm-6">
    	<p class="text-center">{{session('info_create_category_first_message')}}</p>
	</div>

@endif

@if(Session::has('success_create_post_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_create_post_message')}}</p>
	</div>

@endif

@if(Session::has('success_update_post_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_update_post_message')}}</p>
	</div>

@endif

@if(Session::has('success_delete_post_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_delete_post_message')}}</p>
	</div>

@endif

<!-- Comments -->
@if(Session::has('success_comment_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_comment_message')}}</p>
	</div>

@endif

@if(Session::has('success_comment_approved_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_comment_approved_message')}}</p>
	</div>

@endif

@if(Session::has('success_comment_unapproved_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_comment_unapproved_message')}}</p>
	</div>

@endif

@if(Session::has('success_delete_comment_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_delete_comment_message')}}</p>
	</div>

@endif

<!-- Replies -->
@if(Session::has('success_reply_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_reply_message')}}</p>
	</div>

@endif

@if(Session::has('success_reply_approved_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_reply_approved_message')}}</p>
	</div>

@endif

@if(Session::has('success_reply_unapproved_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_reply_unapproved_message')}}</p>
	</div>

@endif

@if(Session::has('success_delete_reply_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_delete_reply_message')}}</p>
	</div>

@endif

<!-- Categories -->
@if(Session::has('success_create_category_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_create_category_message')}}</p>
	</div>

@endif

@if(Session::has('success_update_category_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_update_category_message')}}</p>
	</div>

@endif

@if(Session::has('success_delete_category_message'))
	
	<div class="alert alert-success col-sm-6">
    	<p class="text-center">{{session('success_delete_category_message')}}</p>
	</div>

@endif

<!-- Photos -->
@if(Session::has('success_delete_photos_message'))
	
	<div class="alert alert-success col-sm-6">
		<p class="text-center">{{session('success_delete_photos_message')}}</p>
	</div>

@endif

@if(Session::has('success_delete_photo_message'))
	
	<div class="alert alert-success col-sm-6">
		<p class="text-center">{{session('success_delete_photo_message')}}</p>
	</div>

@endif

resources/views/includes/form_error.blade.php
@if(count($errors)>0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{$error}}</li>
            @endforeach
        </ul>
    </div>
@endif

resources/views/includes/home_footer.blade.php
<hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Blog App {{\Carbon\Carbon::now()->year}}</p>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->

{{-- <!-- jQuery -->
<script src="js/jquery.js"></script>

Bootstrap Core JavaScript
<script src="js/bootstrap.min.js"></script> --}}

<script src="{{asset('js/libs.js')}}"></script>

@yield('scripts')

</body>

</html>

resources/views/includes/home_header.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{{asset('css/blog.css')}}" rel="stylesheet">
    <link href="{{asset('css/libs.css')}}" rel="stylesheet">
    {{-- <link href="css/bootstrap.min.css" rel="stylesheet">

    Custom CSS
    <link href="css/blog-home.css" rel="stylesheet"> --}}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


</head>

</html>

resources/views/includes/home_nav.blade.php
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Blog App</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                @if(Auth::guest())
                    <li>
                        <a href="{{url('/login')}}">Login</a>
                    </li>
                    <li>
                        <a href="{{url('/register')}}">Register</a>
                    </li>
                @else
                    <li>
                        <a href="{{route('admin.index')}}">Admin</a>
                    </li>
                    <li>
                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            Logout
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                @endif
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<div class="container">

resources/views/includes/home_sidebar.blade.php
<div class="col-md-4">

    <!-- Blog Search Well -->
    <div class="well">
        <h4>Blog Search</h4>
        <div class="input-group">
            <input type="text" class="form-control">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                </span>
        </div>
        <!-- /.input-group -->
    </div>

    <!-- Blog Categories Well -->
    <div class="well">
        <h4>Blog Categories</h4>
        <div class="row">
            <div class="col-lg-6">
                <ul class="list-unstyled">
                    @if($categories)
                        @foreach($categories as $category)
                            <li>
                                <a href="#">{{$category->name}}</a>
                            </li>
                        @endforeach
                    @endif
                </ul>
            </div>
            <!-- /.col-lg-6 -->
            {{-- <div class="col-lg-6">
                <ul class="list-unstyled">
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                    <li><a href="#">Category Name</a>
                    </li>
                </ul>
            </div> --}}
            <!-- /.col-lg-6 -->
        </div>
        <!-- /.row -->
    </div>

    <!-- Side Widget Well -->
    <div class="well">
        <h4>Side Widget Well</h4>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
    </div>

</div>

resources/views/includes/tiny_editor.blade.php
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
  var editor_config = {
    path_absolute : "/",
    selector: "textarea",
    plugins: [
      "advlist autolink lists link image charmap print preview hr anchor pagebreak",
      "searchreplace wordcount visualblocks visualchars code fullscreen",
      "insertdatetime media nonbreaking save table contextmenu directionality",
      "emoticons template paste textcolor colorpicker textpattern"
    ],
    toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media",
    relative_urls: false,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>