routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::get('/posts/{post}', ['as'=>'home.post', 'uses'=>'HomeController@post']);

Route::group(['middleware'=>'admin'], function(){
	// Route::get('/admin', ['as'=>'admin.index'], function(){
	// 	return view('admin.index');
	// });
	Route::get('/admin', ['as'=>'admin.index', 'uses'=>'AdminController@index']);

	Route::resource('admin/users', 'AdminUsersController');
	
	Route::resource('admin/posts', 'AdminPostsController');
	
	Route::resource('admin/categories', 'AdminCategoriesController');
	
	Route::resource('admin/photos', 'AdminPhotosController');
	
	Route::delete('admin/delete/photos', 'AdminPhotosController@deletePhotos');
	
	Route::get('admin/comments', 'AdminCommentsController@index')->name('comments.index');
	Route::get('admin/comments/{comment}', 'AdminCommentsController@show')->name('comments.show');
	Route::patch('admin/comments/{comment}', 'AdminCommentsController@update')->name('comments.update');
	Route::delete('admin/comments/{comment}', 'AdminCommentsController@destroy')->name('comments.destroy');

	
	Route::get('admin/comment/replies/{reply}', 'AdminCommentRepliesController@show')->name('replies.show');
	Route::patch('admin/comment/replies/{reply}', 'AdminCommentRepliesController@update')->name('replies.update');
	Route::delete('admin/comment/replies/{reply}', 'AdminCommentRepliesController@destroy')->name('replies.destroy');
	
	Route::get('/profile', ['as'=>'home.profile', 'uses'=>'HomeController@profile']);
});

Route::group(['middleware'=>'auth'], function(){
    Route::post('admin/comment/replies', 'AdminCommentRepliesController@store')->name('replies.store');
    Route::post('admin/comments', 'AdminCommentsController@store')->name('comments.store');
});

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
	\UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::fallback(function(){
    return view('errors.404');
});

// Route::resource('admin/posts', 'AdminPostsController');

// Route::resource('admin/categories', 'AdminCategoriesController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = ['name'];
}

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin')

@section('content')

    <div class="row">
        <div class="col-sm-6">
            @include('includes.form_error')
        </div>
    </div>
    
    <h1>Edit Categories</h1>


    <div class="col-sm-6">

        {!! Form::model($category, ['method'=>'PATCH', 'action'=> ['AdminCategoriesController@update', $category->id]]) !!}
        <div class="form-group">
            {!! Form::label('name', 'Name:') !!}
            {!! Form::text('name', null, ['class'=>'form-control'])!!}
        </div>

        <div class="form-group">
            {!! Form::submit('Update Category', ['class'=>'btn btn-primary col-sm-6 ']) !!}
        </div>
        {!! Form::close() !!}


        {!! Form::open(['method'=>'DELETE', 'action'=> ['AdminCategoriesController@destroy', $category->id]]) !!}


        <div class="form-group">
            {!! Form::submit('Delete Category', ['class'=>'btn btn-danger col-sm-6']) !!}
        </div>
        {!! Form::close() !!}

    </div>


    <div class="col-sm-6">

    </div>

@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin')

@section('content')


    <h1>Categories</h1>

    <div class="row">
        <div class="col-sm-6">
            @include('includes.form_error')
        </div>
    </div>

    <div class="col-sm-6">

        {!! Form::open(['method'=>'POST', 'action'=> 'AdminCategoriesController@store']) !!}
            <div class="form-group">
                {!! Form::label('name', 'Name:') !!}
                {!! Form::text('name', null, ['class'=>'form-control'])!!}
            </div>

            <div class="form-group">
                {!! Form::submit('Create Category', ['class'=>'btn btn-primary']) !!}
            </div>
        {!! Form::close() !!}
	
    </div> 

    <div class="col-sm-6">
        @if($categories)
            <table class="table">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Created Date</th>
                </tr>
                </thead>
                <tbody>

                @foreach($categories as $category)

                    <tr>
                        <td>{{$category->id}}</td>
                        <td><a href="{{route('categories.edit', $category->id)}}">{{$category->name}}</a></td>
                        <td>{{$category->created_at ? $category->created_at->diffForHumans() : 'no date'}}</td>
                    </tr>
                @endforeach

                </tbody>
            </table>

            <div class="row">
                <div class="col-sm-6 col-sm-offset-5">

                    {{$categories->render()}}

                </div>
            </div>

        @endif

    </div> 

@endsection